name: virus2tree
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - biopython
  - lxml
  - scipy
  - pyparsing
  - requests
  - natsort
  - pyyaml
  - filelock
  - dendropy
  - mafft
  - iqtree
  - ngmlr
  - numpy
  - pandas
  - tqdm
  - pyham
  - pysam
  - minimap2
  - seqkit
  - nextgenmap
  - samtools
  - rasusa
  - ete3
  - cython
